ansible_user: ec2-user 
ansible_password: DevOps321

MONGO_IP: mongodb-"{{ env }}".krishnadev.space
CATALOGUE_IP: catalogue-"{{ env }}".krishnadev.space
REDIS_IP: redis-"{{ env }}".krishnadev.space
USER_IP: user-"{{ env }}".krishnadev.space
CART_IP: cart-"{{ env }}".krishnadev.space
MYSQL_IP: mysql-"{{ env }}".krishnadev.space
SHIPPING_IP: shipping-"{{ env }}".krishnadev.space
RABBITMQ_IP: rabbitmq-"{{ env }}".krishnadev.space
PAYMENT_IP: payment-"{{ env }}".krishnadev.space
FRONTEND_IP: frontend-"{{ env }}".krishnadev.space
app_version: v3